repos:
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.1
      hooks:
        - id: pyupgrade
          args: ["--py3-plus"]
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.0
      hooks:
        - id: reorder-python-imports
          args: ["--application-directories", "src"]
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
        - id: flake8
          additional_dependencies:
            - flake8-bugbear
            - flake8-implicit-str-concat
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
        - id: check-byte-order-marker
        - id: trailing-whitespace
        - id: end-of-file-fixer
